### DISCUSSION TITLE
Turning portable builds into appimages is very easy.

### DISCUSSION THREAD

**Discussion by Samueru-sama** [ivan-hc/AM#369] [Ideas]
I just made these two scripts for Ryujinx and DeaDBeeF they only release as portable builds instead of appimages, just copied the way Ivan builds his appimages to make them:

https://pastebin.com/1cewSaxP

https://pastebin.com/NpzeYPgW

I commented in their respective github issues about appimage support, hopefully they implement this, if they don't I will look into hosting them myself in a few days. 

Edit: ended up releasing them: 

https://github.com/Samueru-sama/Ryujinx-AppImage
https://github.com/Samueru-sama/DeaDBeef-AppImage

What other apps come as portable builds but not as appimages so I can try to convert them to appimage?

EDIT: Here are all the appimages made so far: 

https://github.com/Samueru-sama/Zenity-GTK3-AppImage (This one was tricky as zenity needed patches on its source code) 
https://github.com/Samueru-sama/Ryujinx-AppImage
https://github.com/Samueru-sama/DeaDBeef-AppImage (Also added the DeaDBeeF stable build) 
https://github.com/Samueru-sama/rofi-AppImage
https://github.com/Samueru-sama/htop-AppImage

~~However the AppImages that get compiled are being compiled on ubuntu-latests instead of 20.04, as I get meson errors when trying to compile on 20.04~~

EDIT: Fixed!

**Comment by ivan-hc** [comment]
You mean from the database? You should perform a **generic** search of all scripts that contain "*.tar*", "*.zip" or "*.deb" (without asterisks)... or also those that does not contain the *lowercased* "*mage" (the latter is with asterisk).

If they wont, none prevent you to buildAppImages by yourself... none of my 60+ appimages is official (and for some of these I contatcted the owners). In the case they wont, you can proceed with a repo *marked* as Unofficial and keep it until none reclaims.

**Reply by Samueru-sama** [reply]
It was more of a broad questions for "popular" linux apps that still release as portable builds, but what you said works for me as well to start looking.

**Reply by ivan-hc** [reply]
I already know the answer of many of them:"we have not enough resources... I'm ok like this... there is already a Flatpak..." :laughing: 

I jocke, but many developers have a bad opinion about AppImages, because they not always work, they "still rely on libfuse2" and "can't be updated"... all prejudices. "AM" can guarantee for the last two, but not for the first... much depends on how the developer bundles it.

Also Blender's and SuperTuxKart's developers were contrary, they have a portable version of their program, and for them its enough. Also Telegram is just a standalone binary, not an AppImage.

**Reply by Samueru-sama** [reply]
@ivan-hc Oh if you knew the hot takes that I saw recently about appimages, check my recent issue history if you want to find out. 🙃

**Comment by Samueru-sama** [comment]
@ivan-hc I began trying to host the deadbeef appimage, I uploaded the script but now I'm stuck with the github actions, I would really appreciate any help please!

https://github.com/Samueru-sama/deadbeef-appimage

**Reply by ivan-hc** [reply]
all my workflows are the same:
```
name: SAMPLE Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/SAMPLE-appimage/main/SAMPLE.sh
        chmod a+x ./SAMPLE.sh
        ./SAMPLE.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SAMPLE-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: SAMPLE-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build (JuNest Arch Linux-based AppImage)
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              SAMPLE-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}

```

all you have to change are "SAMPLE" and
```
on:
  schedule:
    - cron: "0 16 1/2 * *"
  workflow_dispatch:
```
to choose when to update the app... I've seen that you use
```
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
```
