### ISSUE TITLE
Investigate equivalent functionality of `--home` for formats other than AppImage

### ISSUE THREAD

**Issue by fiftydinar** [ivan-hc/AM#186]
Cleaning home directory from config & cache used by .tar.gz & other packages can be a difficult task.

Let's investigate if it's possible to place those home files in 1 centralized directory, like AppImage does in `package_name.home`.

This would make sure that other apps are cleanly removed from the system too.

**Comment by ivan-hc** [comment]
This is not a task that other apps other than AppImages can perform easily using a CLI like AM/AppMan:

- The mechanics for an AppImage is "create a directory .home with the same name of the AppImage, near the AppImage";
- Universally its enough to run the app into a dedicated directory to use as a $HOME.

For example, create a new directory
```
mkdir test
cd test
```
then you can run
```
HOME=./
```
or better
```
HOME="$(dirname "$(readlink -f $0)")"
```
from now and for the whole terminal session you can run any app into that directory that will be used as a custom $HOME directory.

If we want to implement such a feature, we should change all the installation scripts for portable apps (non AppImages), add a script that will be symlinked to /usr/local/bin that runs the app into a dedicated directory. This would be an huge work to do.

Easier solution? Push more to convert all the portable apps to the AppImage format. I've done this for many of my apps (see the ones built from .deb or archive, at https://github.com/ivan-hc#my-appimage-packages , fr example Dropbox, Skype, Whatsapp Nativefier, Anydesk...). It was not difficult for some of these, but to convert them in AppImage should not be my task. I'de prefer that the upstream developers take care of this.

**Comment by ivan-hc** [comment]
>  We can unofficially make AppImages, but it's the question on how long would that support last compared to official package.

if my workflows in each repository I've created will "[keep to be alive](https://github.com/marketplace/actions/keepalive-workflow)", they shoul be packaged also in case I die. I'm not sure, time two months and I'll be sure if my keepalive workflows are OK

```
name: Github Action with a cronjob trigger
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
```
