### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by Twig6943** [ivan-hc/AM#996]
To help us make adding AppImages quicker and easier, please try to follow the following two syntaxes.

## If available on Github.com
- name signal
- repository https://github.com/signalapp/Signal-Desktop

**Comment by Twig6943** [comment]
an appimage doesnt exist (I was wondering if u could pacakge it)

**Comment by Twig6943** [comment]
ooh :+1:

**Comment by ivan-hc** [comment]
anyway, have you tried to use Archimage? https://github.com/ivan-hc/ArchImage maybe I can help you in case you have doubts

**Comment by ivan-hc** [comment]
It is preferable that whoever builds it knows what is needed to make it work as it should. I have never used Signal. Skype yes (and I have a repo).

**Comment by Twig6943** [comment]
failed w archimage

**Comment by ivan-hc** [comment]
let me do a test

**Comment by ivan-hc** [comment]
I created this script

[signal-desktop-junest.sh.txt](https://github.com/user-attachments/files/17346651/signal-desktop-junest.sh.txt)

Signal is in the arch linux repos https://archlinux.org/packages/extra/x86_64/signal-desktop/ not an AUR package

to create the above script:
1. name: signal-desktop
2. name binary: leave blank, its the same
3. dependences: none
4. include all dependences: y
5. use defaults: y

video:

https://github.com/user-attachments/assets/06308a6d-24db-417f-917c-8e1a9d78fe0b

AppImage is 296 MB

here is what happens when I run it


https://github.com/user-attachments/assets/b0d6474c-c7bc-4df0-bc91-bcde8d764176

to fix it you can start to read the logs and see what files are missing, like this


https://github.com/user-attachments/assets/fed38d05-bf11-4804-9846-93e55e14e6b0

it is looking for a missing module, contained into a package to search on google (or in my case startpage), in this case the package is xapp

all you need to do is to take note of the missing package and then add to dependences, like this

https://github.com/user-attachments/assets/bbe35505-d8f9-489c-9e31-ef5713a7cc3c

and as you can see, xapp is downloaded and then it wil be extracted with all the other packages listed during this process in the "deps" directory

the appimage is increased of 0,1 MB, let we see if it works...




https://github.com/user-attachments/assets/5c832f45-e3fa-4a10-8b16-69f381492685

also this time it is not working, but I've found that there is a missing library "libgnomekbdui", contained in the "libgnomekbd" arch linux package... so I'll do the same as I did with xapp

now the package is 296,2 MB... let we see if it runs...

https://github.com/user-attachments/assets/bad4d6cc-a16c-498b-a9fa-528894c3cb8f

this time it is missing the library "libudev.so", I'll add the keyword "libudev" to $LIBSAVED, to fetch all files containing this word, for this will be added all depending libraries and it too will be bundled in the appimage

in case it is not saved, search the package containing that library as I did with xapp

now the package is 296,3 MB... let se again

https://github.com/user-attachments/assets/bf6ff485-80b7-4c33-a753-19e8c2a08d74

magic!

If the app works, you are good with it, but it is suggested to find missing libraries.

Also, now that you know that it works, you can start debloating (play by running the AppRun script in the AppDir directory, use Baobab or something else to find the size of packages, try to move them elsewhere and run the AppRun, and see if it works... if it is ok, take note of all files you can remove, and the package will be smaller once you add them to the list "ADDITIONAL REMOVALS"

**Comment by ivan-hc** [comment]
The working script I got in the final video is now here https://github.com/ivan-hc/ArchImage/blob/main/drafts/signal-desktop-junest.sh

Now you know how to build an archimage works :)

**Comment by Twig6943** [comment]
@ivan-hc compiling rn (tysm for the script)

**Comment by ivan-hc** [comment]
> @ivan-hc compiling rn (tysm for the script)

???

**Comment by Twig6943** [comment]
I mean packaging**** 

(signal-desktop-junest.sh)

**Comment by ivan-hc** [comment]
Consider this script as a gift

Seriously, I don't want to open more repositories. I have too many to maintain, and each of them has problems.

PS: I posted my comment as a "tutorial", I can't do better than that https://github.com/ivan-hc/ArchImage#tutorial

I've been building them for years and trying to build easy alternatives to package AppImages, adding tutorials and videos. But I've gotten to the point where I've created so many of them, and it's hard to keep up with all of them. Especially when github changes the "workflow" mechanism. I'm doing everything I can to reduce the number of active repositories.

**Comment by Twig6943** [comment]
@ivan-hc wayland doesnt work with the appimage package
![image](https://github.com/user-attachments/assets/50ac080d-d1de-4d90-8054-086da282c6ac)
![image](https://github.com/user-attachments/assets/adacfc52-3687-43b5-b63f-3968c8cdb52c)

**Comment by ivan-hc** [comment]
try to add "wayland" as a dependency, or as a keyword

I am still on X11 btw (XFCE4.18).

**Comment by Twig6943** [comment]
DEPENDENCES="**wayland** ca-certificates xapp libgnomekbd"

Still the same result with the --ozone-platform=auto

**Comment by Twig6943** [comment]
also https://github.com/Twig6943/Signal-AppImage/releases/tag/1.0 (WIP pkg) (WIP cuz wayland doesnt work like I said)

**Comment by ivan-hc** [comment]
run it with LD_DEBUG=libs and see the missing library

you need to read the whole log and see where there is an error message, for example, in the appimage you provided, I've found that it have not "libxklavier"

![Istantanea_2024-10-12_01-06-22 png](https://github.com/user-attachments/assets/17401a96-4f6a-4c49-9df0-1a0406257a89)

note the side bar of my terminal, I'm in the middle of the log

**Comment by ivan-hc** [comment]
NOTE, to made this search may take a whole day, also for me.

You need to read and understand each line. The last one I have pointed, as all of them, mean that the program is looking for a library to load. In this case "libxklavier". If it is in "junest-backups" you can add "libxklavier" in LIBSAVED as a keyword, else add directly the dependency that brings that library with it (in this case "[libxklavier](https://archlinux.org/packages/extra/x86_64/libxklavier/)").

**Comment by ivan-hc** [comment]
> NOTE, to made this search may take a whole day, also for me.
> 
> You need to read and understand each line. The last one I have pointed, as all of them, mean that the program is looking for a library to load. In this case "libxklavier". If it is in "junest-backups" you can add "libxklavier" in LIBSAVED as a keyword, else add directly the dependency that brings that library with it (in this case "[libxklavier](https://archlinux.org/packages/extra/x86_64/libxklavier/)").

I'm not sure if it is enough to solve the issue with wayland. You need to try and try and re-try until it works the way you want.

**Comment by ivan-hc** [comment]
uhm...just noticed that your script https://github.com/Twig6943/Signal-AppImage/blob/main/signal-desktop-junest.sh is different from this I linked at the end of my tutorial https://github.com/ivan-hc/ArchImage/blob/main/drafts/signal-desktop-junest.sh have you used the correct one?

**Comment by Twig6943** [comment]
I tried your script last night but wayland didnt work w that one (app still works fine via xwayland tho) so I edited the script a bit to make wayland work but still no dice

**Comment by ivan-hc** [comment]
uhm... if you use other archimages I created and they work in wayland, you should check what I added in that scripts, it may help

for what I know, xwayland semms to be the easier way to made it work, but maybe I'm wrong, I don't use Wayland at all... I should wait in december or january I guess, for xfce4.20

**Comment by Twig6943** [comment]
Well I'm too lazy to get the app to run with wayland could u add it to AM's main repo regardless? 
https://github.com/Twig6943/Signal-AppImage/releases

**Comment by ivan-hc** [comment]
Hi, create a /.github/workflows/CI.yml file in your repo with this content
```
name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install libfuse2 desktop-file-utils
        chmod a+x ./*junest.sh
        ./*junest.sh
        mkdir dist
        mv *AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
```
and then go in the "Actions" tab of your repo and run it, it should update the build every day without in authomatic, to tag "continuous"
